apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "st-helm.fullname" . }}-backend
  labels:
    type: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend_image.repository }}:{{ .Values.backend_image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.backend_image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ['sh', '-c', "sleep 100m"]

