apiVersion: v1
kind: Service
metadata:
  name: {{ include "st-helm.fullname" . }}-database
  labels:
    type: database
spec:
  ports:
    - port: 3306
      targetPort: http
  selector:
    type: database
