apiVersion: v1
kind: Service
metadata:
  name: {{ include "st-helm.fullname" . }}-frontend
  labels:
    type: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    type: frontend
